backend:
  name: github
  repo: antcliffr12/Cupp

media_folder: static/assets
public_folder: assets

collections: # A list of collection the CMS should be able to edit
  - name: home
    label: Home Page
    folder: src/pages/home
    create: true
    fields:
      - {
          label: Tempalte Key,
          name: templateKey,
          widget: hidden,
          default: homePage,
        }
      - { label: Title, name: title, widget: string }
      - { label: Image, name: image, widget: image }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }

  - name: page
    label: Pages
    folder: src/pages
    create: true
    fields:
      - {
          label: Tempalte Key,
          name: templateKey,
          widget: hidden,
          default: default-page,
        }
      - { label: Title, name: title, widget: string }
