backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections: # A list of collection the CMS should be able to edit
  - name: page
    label: Pages
    folder: page
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
